"""coluna mail

Revision ID: 657cd95737b5
Revises: 
Create Date: 2022-11-08 19:33:58.640765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657cd95737b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
